name: Build MarketPulse Microservices

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Build market-data
      - name: Build market-data
        working-directory: ./TradingApp/market-data
        run: mvn clean package -B

      # Build processor
      - name: Build processor
        working-directory: ./processor
        run: mvn clean package -B

      # Build ui-desk
      - name: Build ui-desk
        working-directory: ./ui-desk
        run: mvn clean package -B

      # Upload JAR artifacts
      - name: Upload market-data JAR
        uses: actions/upload-artifact@v4
        with:
          name: market-data-jar
          path: TradingApp/market-data/target/*.jar

      - name: Upload processor JAR
        uses: actions/upload-artifact@v4
        with:
          name: processor-jar
          path: processor/target/*.jar

      - name: Upload ui-desk JAR
        uses: actions/upload-artifact@v4
        with:
          name: ui-desk-jar
          path: ui-desk/target/*.jar